language: python
python:
- '3.6'
env:
- TOXENV=py36
- TOXENV=flake8
- TOXENV=build
install:
- pip install tox
script: tox
services:
- postgresql
deploy:
  provider: pypi
  distributions: bdist_wheel
  user: rmb938
  password:
    secure: qFX8R9hokU3iEEdIe28EyR/C39DxA/Rgbx3xQZMDBRMPxNWx2uRyF20qQeKG4rOA+Sccap2CqZi0yWgMUOkULJceTH3TW4DoAGc9/a/Wo5bc6KNUGPX89qfx8J03ZWLifvfs67rXnhgtDpH7GYdq0NYyx3PvGxznbK+PZhpPZNXJjYjokiuOpJxxPNAu5WXTy0qyKjfX75GfQtrH2eE0lpYmKdKZeSOKheQ0UgCznvD9iLxV6QVetpfk5g3k6yg/91KP6stNNGc9SzaaTGLQ/4jdQaXlpE2B20iVYepXPP3nZAKQsn/KAF/5BS0S19ZQ3gZCTzlbeaMypJbaBYHOuMPmeVw7Yz4ASmHyzDFNDBzDeBCxY8n2/hOR90zLyBMOOK2JsnBBJBhQSJg/Mw94iCzj9G80OAFZukuSEheH61Du5a5GXj85d4rGi4A8PJ7q2NzFkZOeVVXKLDe8fMpfleO0hYyMFJCmsqsVvRkgOvNo1NzOMveUSLGuo1ecAr3Uh/GD8xTNjYfTGLGPgAMLt2H0QYxBw/ixyGrSxxiRCA9eR5Yi3BR9H+Adjk7zozsv+3s62gk/saPBaUWJAgPENG53At5ih9h79Kn0sN4rR9+I6HMsK/8QO50WXju7RRqCKdsge6xpXVI13q6ziY62nhvcr11PBHM3uGImzzD0wHc=
  on:
    tags: true
